version: '3'
services:
  syseng:
    image: beorn7/syseng-challenge
    ports:
      - "8080:8080"
    networks:
      - examplnet

  syseng_exporter:
    build: ../..
    image: varankinv/syseng-exporter
    command: ['/bin/syseng_exporter', '--syseng.stats-uri=http://syseng:8080/stats']
    networks:
      - examplnet

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - examplnet

networks:
  examplnet:
