global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'syseng'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'syseng-exporter'
    static_configs:
      - targets: ['syseng_exporter:8081']
