apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: syseng
  labels:
    app: syseng
spec:
  replicas: 1
  template:
    metadata:
      name: syseng
      labels:
        app: syseng
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: syseng
          image: beorn7/syseng-challenge
          ports:
            - name: http
              containerPort: 8080
        - name: syseng-exporter
          image: varankinv/syseng-exporter
          imagePullPolicy: Always
          command: ["/bin/syseng_exporter", "--syseng.stats-uri=http://localhost:8080/stats"]
          ports:
            - name: exporter
              containerPort: 8081

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /var/lib/prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-yml
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-yml
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        monitor: 'syseng'

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'syseng-exporter'
        scheme: http
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod

---
apiVersion: v1
kind: Service
metadata:
  name: syseng-svc
  labels:
    name: syseng
spec:
  selector:
    app: syseng
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: exporter
      port: 8081
      protocol: TCP
      targetPort: exporter

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  type: LoadBalancer
